steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud compute ssh $_VM_NAME --zone=us-central1-a --command "cd /opt/odoo18/odoo-server/custom_addons && git pull origin main && sudo systemctl restart odoo18"
