steps:
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
          gcloud compute ssh "$_VM_NAME" --zone=us-central1-a --command "
            cd /opt/odoo18/odoo-server/custom_addons &&
            rm -rf * && \
            git clone https://github.com/avinash2196/OddoDemo . && \
            /opt/odoo18/odoo-server/venv/bin/python3 /opt/odoo18/odoo-server/odoo-bin \
              -c /etc/odoo18.conf -d "$_DB_NAME" -u all && \
            sudo systemctl restart odoo18
          "
options:
  logging: CLOUD_LOGGING_ONLY
